plugins {
    id 'net.neoforged.moddev'
}

repositories {
    maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
}

neoForge {
    neoFormVersion = project.neoform_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }
}

dependencies {
    compileOnly 'org.spongepowered:mixin:0.8.7'
}
